spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?createDatabaseIfNotExist=true
    username: root
    password: root@1234
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2hr
    refreshTokenExpiration: 604800 #7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: http://localhost:4242
payment:
  service: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761
