spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?createDatabaseIfNotExist=true
    username: root
    password: root@1234
  jpa:
    show-sql: true

websiteUrl: http://localhost:4242
payment:
  service: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761
