spring:
  application:
    name : store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?createDatabaseIfNotExist=true
    username: root
    password: root@1234
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-curries : USD, EUR, GPB
payment:
  service: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761