spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 #15min
    refreshTokenExpiration: 604800 #7d
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
payment:
  service: paypal
mail:
  host: https://smtp.gmail.com
  port: 5761
